### Create a User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "1@gmail.com",
    "password": "Surajngh"
}

### Signin a User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "1@gmail.com",
    "password": "Surajngh"
}

### who am i
GET http://localhost:3000/auth/whoami



### signout
POST http://localhost:3000/auth/signout



### find a User by id
GET http://localhost:3000/auth/2


### find a User by email
GET http://localhost:3000/auth?email=suraj@gmail.com

### Update a User
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "suraj@gmail.com",
    "password": "SurajSingh"
}


### Remove User
DELETE http://localhost:3000/auth/1
